# name | shape | palette | accent | features | face | note
# family order for kids: green, sweet, greasy, spicy, sour (= the 2nd food)
SET_A = {
 'title': 'New set A: clean shapes',
 'green': {
  'baby': 'Moss|dome|green|-|sprout|dot|A little hill that grew a leaf.',
  'kids': [
   'Fern|bean|green|-|leaf2|lid|Tall, quiet, always looking down at you.',
   'Bluebell|bell|green|sweet|cap|dot|Wears a blue hat it never takes off.',
   'Olivo|egg|olive|greasy|stem:green|side|Oily, shiny, side-eyeing.',
   'Rootie|pear|green|spicy|base|flat|Red roots, green head.',
   'Squee|ball|lime|-||squint|Squeezed once. Never again.'],
  'adults': [
   'Canopy|puff|green|-|tuft|lid|Carries its own shade around.',
   'Thicket|box|green|olive|spikes:olive|dash|Prickly, but only on top.',
   'Mosslith|tallbox|char|green|cap|ring|A stone that moss adopted.',
   'Hyacinth|tower|green|sweet|petals|sleep|Rings at dawn. Nobody hears it.',
   'Dewdrop|drop|teal|-|drop|o|Always about to fall off something.',
   'Indigrow|peanut|sweet|green|leaf2|stern|The blue went all the way down.',
   'Pressly|disc|olive|greasy|band|bored|Flattened by a press. Still unbothered.',
   'Pitkin|egg|olive|choc|belly|dot|Keeps its stone inside, just in case.',
   'Glossum|blob|olive|gold|sparkles|lid|So shiny you can see yourself.',
   'Mandrake|bean|coral|green|leaf2 arms|o|Screams, but only on Tuesdays.',
   'Beetle Root|ball|magenta|green|leaf2|stern|Deep purple attitude.',
   'Wasabun|bun|mint|green|blush|fang|Green, soft, and it bites.',
   'Pithy|diamond|lime|cream|belly|lid|Sharp edges, soft middle.',
   'Brineleaf|wedge|teal|green|fins|squint|Seaweed that learned to swim.',
   'Sorrel|onion|green|sour|tip|dash|Looks like spinach, tastes like lemon.'],
 },
 'sweet': {
  'baby': 'Nib|kiss|sweet|-||lid|A chocolate drop, cool to the touch.',
  'kids': [
   'Mintle|kiss|sweet|mint|tip|dot|Minty tip, cold heart.',
   'Cocoon|egg|navy|-||sleep|Wrapped up in itself.',
   'Pralo|mochi|sweet|gold|band|side|A nutty layer hiding inside.',
   'Dusk|drop|purple|-||lid|Chilli turned the chocolate purple.',
   'Plumb|ball|sweet|lilac|half|flat|Half plum, half thought.'],
  'adults': [
   'Glacio|tallbox|ice|sweet|base|dash|A block of minty ice.',
   'Frostmoss|dome|sweet|mint|spikes|lid|Frost grows on it in summer.',
   'Lull|bean|mint|sweet|cap|sleep|Puts you to sleep. Itself first.',
   'Nocturne|ball|navy|-|wings:navy|ring|Only flies when the lights go out.',
   'Velvet|mochi|navy|purple|belly|lid|Too soft to take seriously.',
   'Moonbean|bean|navy|cream|tip|sun|Has a tiny moon on top.',
   'Nougat|box|cream|sweet|band|bored|Layers on layers on layers.',
   'Toffin|puff|gold|sweet|drip|side|Melts a bit when it is nervous.',
   'Brittle|diamond|gold|-|crack|squint|Snaps if you look at it wrong.',
   'Umbra|wedge|purple|char|wings:char|dot|A moth made of evening.',
   'Cayenna|kiss|sweet|spicy|tip flame|fang|Hot centre, cool shell.',
   'Twilite|egg|purple|navy|diag|lid|Half day, half night.',
   'Prunella|puff|purple|-||bored|Wrinkled and proud of it.',
   'Bramble|peanut|navy|purple|spikes seeds|stern|Picks fights with hedges.',
   'Sloe|ball|navy|lilac|tip|flat|The slowest pal in the tree.'],
 },
 'greasy': {
  'baby': 'Glob|loaf|greasy|-||side|A warm puddle with opinions.',
  'kids': [
   'Frond|loaf|greasy|green|leaf2|dot|A fried leaf for a hat.',
   'Glaze|dome|greasy|sweet|drip|lid|Blue glaze dripping, unbothered.',
   'Puddle|disc|gold|-||sleep|Spreads out to relax.',
   'Sizzle|bun|rust|-|steam|squint|Too hot to touch, too lazy to cool down.',
   'Malty|box|greasy|sour|cap|bored|Vinegar on top. Always.'],
  'adults': [
   'Tempo|puff|greasy|green|leaf2|dash|Crunchy on the outside, calm inside.',
   'Fritto|bun|gold|green|band|side|Wears a green belt to dinner.',
   'Hushpup|bean|greasy|-|ears|o|A fried puppy that whispers.',
   'Cruller|twin|greasy|sweet|cap|lid|Twins that never agree.',
   'Moonpie|disc|sweet|greasy|base|sun|A pie that orbits the table.',
   'Combo|box|gold|sweet|hstripes|dot|A bee would live here.',
   'Gilda|dome|gold|-|sparkles|lid|Dripping in gold, says nothing.',
   'Lumpo|puff|greasy|-||bored|Lumpy and fine with it.',
   'Slick|wedge|gold|char|base|side|Leaves a trail everywhere.',
   'Tandoor|bell|rust|char|base flame|stern|A tiny oven with a job to do.',
   'Popple|puff|cream|greasy|spots|o|Pops when startled.',
   'Rizo|peanut|coral|rust|band|fang|Smoky, spicy, slightly sausage.',
   'Kettlo|tallbox|greasy|sour|cap arms|dash|A crisp packet that came alive.',
   'Gillie|wedge|greasy|sour|fins tail|side|Half a fish, all batter.',
   'Crumbly|bun|cream|sour|base crack|bored|Sourdough with a crack in it.'],
 },
 'spicy': {
  'baby': 'Ember|=ember_calm|spicy|-||flat|The Ember you liked, with a calm Picklet-style face.',
  'kids': [
   'Jalo|bean|green|spicy|tip|dot|Green jacket, red hat.',
   'Garnet|diamond|spicy|sweet|half|lid|Half ruby, half sapphire.',
   'Wingo|egg|rust|-|arms|side|Flaps its little arms when hungry.',
   'Cinder|drop|spicy|-|flame|flat|A candle that walks around.',
   'Tamarin|pear|coral|sour|cap|squint|Sweet, sour, hot. Pick one.'],
  'adults': [
   'Pobble|bean|char|green|tip|lid|Roasted, dark, very chill.',
   'Spindle|tower|green|spicy|tip|dash|Stacked thin and very tall.',
   'Thornet|cone|green|spicy|spikes|stern|A cactus that ate a chilli.',
   'Cinnabar|box|spicy|sweet|diag|dot|A red brick with a blue corner.',
   'Maroona|ball|magenta|navy|ring|ring|Has its own little planet ring.',
   'Plume|drop|purple|sweet|flame:sweet|lid|Burns blue. Very hot.',
   'Firewing|egg|spicy|greasy|wings|stern|Takes off when it gets excited.',
   'Crackle|puff|rust|greasy|spots|o|Crackles when you pick it up.',
   'Drumm|pear|rust|cream|base|side|Drums on the table all day.',
   'Calder|cone|char|spicy|tip|dash|A sleeping volcano. Mostly sleeping.',
   'Kindle|bean|spicy|gold|flame twig|sleep|Glows softly at night.',
   'Ashby|dome|char|cream|spots|lid|What is left after the fire.',
   'Picantine|pear|spicy|sour|leaf2:sour|fang|Bites, then apologises.',
   'Hotpot|bun|spicy|sour|band steam|squint|Simmers all day long.',
   'Fermi|tallbox|coral|sour|hstripes bubbles|bored|Bubbling quietly in a corner.'],
 },
 'sour': {
  'baby': 'Picklet|=picklet|sour|-||flat|Kept exactly as it is.',
  'kids': [
   'Gherk|bean|sour|green|spots|flat|Covered in little green bumps.',
   'Fizz|ball|sour|sweet|base bubbles|o|Fizzes when shaken. Do not shake.',
   'Dilly|loaf|sour|greasy|band|lid|Lies flat, smells of dill.',
   'Tingle|drop|sour|spicy|tip|squint|Makes your tongue buzz.',
   'Pucker|blob|lime|-||pout|Pucker level: maximum.'],
  'adults': [
   'Cuke|tallbox|green|sour|stripes|dash|Cool as a cucumber. It is one.',
   'Brinewort|puff|olive|-|leaf2|lid|Grew in a jar of brine.',
   'Knobble|peanut|sour|green|spikes|stern|Knobbly from head to toe.',
   'Sodapop|tallbox|sweet|sour|cap bubbles|dot|A can of something fizzy.',
   'Tartlet|bun|sour|sweet|tip|lid|A tart with a blue top.',
   'Sugarshock|drop|lilac|-|sparkles|o|Too much sugar on top of sour.',
   'Batterdill|loaf|greasy|sour|cap|side|A fried pickle having a nap.',
   'Saltine|box|cream|-|seeds|bored|A cracker that came alive.',
   'Picklejar|tower|olive|cream|bubbles|sleep|Kept in a jar too long.',
   'Zapple|diamond|sour|spicy|crack|ring|Tastes like a battery.',
   'Galanga|onion|sour|spicy|tip twig:green|lid|A root with a temper.',
   'Shocko|puff|lime|spicy|spots|o|Electric to the touch.',
   'Yuzuki|ball|gold|sour|cap|sleep|A sleepy citrus.',
   'Acida|drop|lime|-|drop|side|Even the drop it sheds is sour.',
   'Sourpuss|blob|sour|-|ears|bored|A cat, sort of.'],
 },
 'mutants': [
  'Circuit Fern|tallbox|green|metal|leaf2:metal chip|visor|Ate a microchip. Now it photosynthesises in binary.',
  'Spore|puff|goo|-|antennae|tri|Ate alien goo. Spreads by sneezing.',
  'Cryo Nib|kiss|metal|sweet|tip bolts|visor|Frozen chocolate on a steel frame.',
  'Galaxium|ball|navy|lilac|ring sparkles|one|A tiny night sky in a ball.',
  'Gear Glob|loaf|metal|greasy|band bolts|visor|Runs on old fry oil.',
  'Oozer|blob|goo|greasy|drip|tri|Leaks a bit everywhere.',
  'Thermo|drop|metal|spicy|tip antenna:metal|visor|Reads its own temperature, all day.',
  'Nova|drop|purple|-|flame:goo|one|A green flame from a far planet.',
  'Volt|box|metal|sour|cap chip|visor|A battery with feelings.',
  'Acidrift|twin|goo|sour|antennae|ring|Two blobs that drifted in from space.'],
 'legends': [
  'Elderroot|puff|green|-|leaf2 petals:pink halo|sun|The oldest tree in the gut.',
  'Midnight|kiss|navy|sweet|ring:sweet halo sparkles|sun|Pure dark chocolate, pure night.',
  'Aurum|dome|gold|-|crown sparkles|lid|Fried in liquid gold.',
  'Solaris|ball|flame|-|flame halo wings:flame|sun|A small sun that sits in your hand.',
  'Leviathan|wedge|lime|-|tentacles fins|one|The sour king of the deep.'],
}

SET_B = {
 'title': 'New set B: odd creatures',
 'green': {
  'baby': 'Bud|bean|green|-|leaf2|big|A seed that stood up.',
  'kids': [
   'Thistle|egg|green|purple|spikes:purple|lid|Pretty, but do not hug it.',
   'Umbel|dome|cream|sweet|mushcap|dot|A blue mushroom that walks.',
   'Toady|loaf|olive|-|feet|side|Fried a fly once. Still proud.',
   'Torchleaf|bean|green|-|flame|o|A leaf that caught fire and kept going.',
   'Hopper|egg|lime|-|longears|lid|Jumps when it tastes something sour.'],
  'adults': [
   'Burr|puff|green|-|spikes|dash|Sticks to your socks.',
   'Hedgling|egg|choc|green|spikes:green feet|big|A hedgehog wearing a hedge.',
   'Conifer|cone|olive|-|hstripes|sleep|Hibernates standing up.',
   'Parasol|bean|cream|sweet|mushcap|lid|Carries its own umbrella.',
   'Morel|tower|choc|-|spots|bored|Wrinkly mushroom, wrinkly mood.',
   'Glowcap|dome|teal|lime|mushcap sparkles|ring|Glows in the dark, a little.',
   'Croakley|mochi|olive|-|feet arms|bored|Croaks once a day. That is enough.',
   'Newtle|bean|coral|-|tail feet|side|A newt with somewhere to be.',
   'Mudskip|disc|olive|-|fins|o|Walks on its fins.',
   'Firefly|egg|char|greasy|base wings:white antennae|dot|Lights up its bottom, politely.',
   'Salamo|loaf|spicy|green|tail feet|lid|Lives in the fire, naps in the fire.',
   'Fernace|puff|green|-|flame|stern|A bush that is always on fire.',
   'Cricket|bean|lime|-|antennae legs|dash|Chirps in perfect rhythm.',
   'Leapling|egg|green|-|longears feet|o|Jumps over everything.',
   'Prayer|tallbox|lime|-|arms antennae|ring|Very patient. Very still.'],
 },
 'sweet': {
  'baby': 'Truff|dome|sweet|-|stem:choc|big|A blue chocolate drop with a cocoa stalk.',
  'kids': [
   'Pippin|egg|sweet|mint|wings:mint|big|A cocoa bird.',
   'Velour|mochi|navy|-|ears|sleep|A sleepy chocolate cat.',
   'Grid|box|sweet|gold|hstripes|side|A waffle that thinks in squares.',
   'Hornet|bean|purple|spicy|horns:spicy|dot|Has little horns but means well.',
   'Tadpole|drop|sweet|lilac|tail|o|Swims in hot chocolate.'],
  'adults': [
   'Jayde|egg|navy|mint|wings tuft|lid|Steals shiny things.',
   'Owlet|ball|sweet|cream|ears belly|ring|Up all night, every night.',
   'Nightjar|disc|navy|-|wings|sleep|A bird that sleeps flat.',
   'Panthos|mochi|char|-|ears tail|lid|A dark chocolate panther.',
   'Lynxy|bean|navy|lilac|ears belly|side|Ears that hear the fridge open.',
   'Dozer|loaf|navy|-|ears|sleep|A cat in loaf mode.',
   'Cubit|box|gold|sweet|base|dash|A perfect cube. Do not touch the corners.',
   'Tilekin|tallbox|sweet|cream|diag|big|Stacks itself when bored.',
   'Stackle|tower|gold|sweet|band|bored|Three pancakes in a trench coat.',
   'Beetle|dome|purple|-|antennae legs|dot|A shiny purple beetle.',
   'Imp|pear|purple|-|horns tail|pout|A little devil that is not very good at it.',
   'Scarab|egg|navy|gold|half legs|ring|Rolls things around for fun.',
   'Axolot|bean|pink|sweet|fins|big|Smiles on the inside.',
   'Medusa|dome|lilac|-|tentacles|sleep|Drifts around, stings no one.',
   'Puffer|ball|sweet|-|spikes|o|Puffs up when surprised.'],
 },
 'greasy': {
  'baby': 'Tater|mochi|greasy|-|nubs|lid|A hot potato that will not be passed.',
  'kids': [
   'Podling|bean|green|greasy|base|flat|A pea pod dipped in oil.',
   'Bruin|ball|greasy|sweet|ears belly|dot|A honey bear with blue honey.',
   'Blubber|mochi|gold|-|fins|sleep|A seal that loves the deep fryer.',
   'Hothog|bun|rust|-|spikes|lid|A hedgehog with hot quills.',
   'Chipmonk|bean|greasy|sour|belly ears|o|Stores chips in its cheeks.'],
  'adults': [
   'Peapod|twin|green|-||big|Two peas, one opinion.',
   'Edamaman|peanut|olive|-||lid|Salty, steamed, chill.',
   'Leek|tower|white|green|tip|dash|Tall, pale, and a bit dramatic.',
   'Grizzle|puff|rust|-|ears|bored|A big bear, a small mood.',
   'Pandough|ball|white|char|ears belly|dot|A panda made of dough.',
   'Honeypot|bell|gold|sweet|cap|sleep|Fell asleep in the honey.',
   'Walrusk|mochi|cream|-|stache fins|lid|A walrus with a fine moustache.',
   'Otterly|bean|greasy|-|tail arms|o|Floats on its back holding snacks.',
   'Sirenia|disc|lilac|-|fins|sleep|A sea cow, peacefully drifting.',
   'Porcupyre|puff|rust|-|spikes:flame|stern|Quills like matchsticks.',
   'Armadill|dome|greasy|rust|shell hstripes|big|Rolls into a ball when spooked.',
   'Scalen|egg|rust|greasy|shell|side|A pangolin in a fried coat.',
   'Acornet|egg|choc|greasy|cap stem|dot|An acorn with a crunchy hat.',
   'Squirrely|bean|greasy|-|tail ears|lid|Hides snacks and forgets where.',
   'Cheeks|puff|cream|greasy|cap|pout|Cheeks full, mouth closed.'],
 },
 'spicy': {
  'baby': 'Ember|=ember:big|spicy|-||big|The original Ember: same body, calmer face, no grin.',
  'kids': [
   'Pup|bean|green|spicy|ears:spicy|dot|A chilli puppy.',
   'Dotty|dome|spicy|sweet|spots:sweet|big|A ladybird with blue spots.',
   'Pincher|disc|coral|-|arms antennae|side|Pinches gently, mostly.',
   'Drake|egg|spicy|-|wings tail|lid|A baby dragon, trying its best.',
   'Shrimpo|bean|coral|-|antennae tail|o|Bends in half when nervous.'],
  'adults': [
   'Kitsu|egg|greasy|white|belly ears tail|lid|A fire fox with a white chest.',
   'Yipper|ball|spicy|-|longears|o|Small dog, big ears.',
   'Howl|bean|rust|-|ears|squint|Howls at the microwave light.',
   'Ladyluck|dome|spicy|char|spots wings:white|dot|A lucky ladybird.',
   'Firebug|egg|spicy|char|cap antennae|dash|Warm to the touch, like a radiator.',
   'Weevil|bean|purple|-|antennae legs|lid|A long nose for finding snacks.',
   'Clawdia|bean|spicy|-|arms antennae|stern|Stands up straight, claws ready.',
   'Hermit|dome|coral|cream|shell|side|Lives in a borrowed shell.',
   'Scampi|disc|coral|-|legs|big|Lots of legs, no plans.',
   'Wyv|egg|char|spicy|belly wings tail|lid|A dark dragon with a red belly.',
   'Komodo|loaf|rust|-|tail feet spikes|bored|Lies in the sun, unbothered.',
   'Gecko|bean|coral|-|tail feet|ring|Sticks to the walls of the gut.',
   'Prawnz|tower|magenta|-|antennae|one|One big eye, lots of colour.',
   'Octopepper|dome|spicy|-|tentacles|sleep|Eight spicy legs.',
   'Polyp|puff|coral|-|tentacles|dot|Part of a reef, part of a pal.'],
 },
 'sour': {
  'baby': 'Picklet|=picklet|sour|-||flat|Kept exactly as it is.',
  'kids': [
   'Ribbit|mochi|lime|-|feet|lid|A sour frog.',
   'Owlime|ball|sour|sweet|ears belly|ring|An owl with a sour stare.',
   'Eely|bean|sour|greasy|band fins|side|Slippery, a bit oily.',
   'Buzz|egg|sour|char|hstripes wings:white antennae|big|A sour wasp that never stings.',
   'Citrine|diamond|lime|-||squint|A sour crystal.'],
  'adults': [
   'Toadle|mochi|olive|sour|spots|bored|A toad with sour spots.',
   'Tango|bean|lime|spicy|feet|o|A tree frog with red feet.',
   'Axel|loaf|sour|-|fins tail|dot|Swims slowly, thinks slowly.',
   'Hoot|egg|sour|cream|belly ears|ring|Turns its head all the way round.',
   'Moonowl|ball|sweet|sour|belly ears|lid|Only comes out at night.',
   'Barnaby|bean|cream|sour|cap ears|dash|A barn owl with a lemon hat.',
   'Moray|tower|sour|greasy|fins|side|Peeks out of the rocks.',
   'Lumo|egg|navy|sour|antenna:sour|one|Brings its own light to the deep.',
   'Brinny|disc|sour|-|fins tail|lid|A small fish from a pickle jar.',
   'Hornetta|bean|greasy|char|hstripes wings:white|stern|Buzzes in short sentences.',
   'Darter|tallbox|teal|-|wings:white|big|A dragonfly in a hurry.',
   'Lumen|egg|cream|sour|cap wings:cream antennae|sleep|A moth that found the lamp.',
   'Prism|diamond|gold|-|sparkles|ring|Splits light into flavours.',
   'Quartzy|box|lime|-|crack|lid|A cracked crystal. Still sharp.',
   'Geode|egg|char|lime|belly|dot|A plain rock with a sour crystal inside.'],
 },
 'mutants': [
  'Botanoid|bean|metal|green|leaf2 chip|visor|Ate a microchip. Grows circuits instead of leaves.',
  'Zorb|ball|goo|-|antennae|tri|Ate alien goo. Three eyes, no worries.',
  'Cocoa-9|kiss|metal|sweet|cap bolts|visor|A chocolate robot, model 9.',
  'Abyssa|dome|navy|goo|tentacles:goo|one|Something from the dark bottom of space.',
  'Fryborg|loaf|metal|greasy|drip antenna:metal|visor|Half fryer, half pal.',
  'Gloopy|puff|goo|greasy|spots|tri|Absorbs anything greasy.',
  'Blazetron|drop|metal|-|flame bolts|visor|A flame thrower that only warms hands.',
  'Xenochili|bean|purple|goo|antennae:goo tentacles:goo|tri|A chilli from another planet.',
  'Acidbot|box|metal|sour|cap chip|visor|Runs on lemon juice.',
  'Glorp|blob|goo|-||one|Just a blob. From space.'],
 'legends': [
  'Grovekeeper|dome|green|-|leaf2 petals:pink halo|sun|A forest spirit that keeps the gut green.',
  'Nightwhale|wedge|navy|-|fins tail sparkles|sun|Swims through the night sky.',
  'Sunbear|ball|gold|cream|ears belly crown|lid|The king of fried things.',
  'Infernadrake|egg|spicy|-|wings:flame tail crown flame|star|The dragon of every chilli ever eaten.',
  'Krakenade|dome|lime|-|tentacles crown|one|The sour giant from the bottom of the jar.'],
}
