# Sheet 4 (2026-10-11): the user's picks from sheets 1-3, arranged into one tree of 120.
# Same line format as sets3.py. Kids in order of the 2nd food (green, sweet, greasy, spicy, sour);
# 3 adults per kid: ROOT/PEAK/CHAOS (mixed kid) or ULTRA/BLOOM/CLASH (pure kid).
# Moved to another family (where it fits better): Komainu -> green; Cocoa Fire, Kuri, Bruin ->
# sweet; Hermit (now with a lemon shell), Anemone, Octopepper, Teru Teru, Karakasa -> sour.
# User tweaks: Waffle bigger, Oden with Kebab's face, Axel without the green tail, Scarab round.
# Round 2 (2026-10-11): every line now shares something kid -> adult (the same creature grown up,
# the same dish bigger, or the same world: Kiwi -> Kiwi Bird, Usagi -> Usagi Manju / Yamabiko,
# Teru Teru -> Omamori / Kokeshi / Karakasa (charms), Hermit -> Anemone / Calamari / Octopepper
# (the sea)...); Sakura Mochi and Yuzu Lord replaced (Usagi Manju, Omamori).
# NEW (11, to fill the gaps): listed in NEW. Mutants and legends: placeholders (user: change later).
from sets3 import BUD, EMBER, PICKLET

NEW = ['Yomogi', 'Usagi Manju', 'Pistachio', 'Bonbon', 'Ume Onigiri', 'Granny', 'Lemon Sweet',
       'Cream Soda', 'Calamari', 'Lemon Ant', 'Omamori']

SHEET4 = {
 'title': 'Sheet 4: your picks',
 'sub': 'your favourites from sheets 1-3 in one tree; NEW = 11 new pals to fill the gaps; mutants and legends are placeholders',
 'new': NEW,
 'green': {'baby': BUD, 'kids': [
   'Peapod | pod | green/lime | | dot flat | Three peas, one opinion.',
   'Usagi | mochi | green/sweet | ears_bunny | sleep w | Pounds mochi under the moon.',
   'Kakiage | pebble | crust/green | crust speckle:green | heavy flat | A tempura fritter that walks.',
   'Tengu | egg | green/spicy | face_patch:spicy longnose:spicy feather:wood | stern flat | A forest goblin with a red face.',
   'Kiwi | egg | wood/lime | face_patch:lime | dot flat | Fuzzy outside, sour inside.'],
  'adults': [
   'Avocado | pear | green/olive | belly:wood | dot flat | A pea that grew up: green, big, proud of its stone.',
   'Melon Pan | bun | lime/crust | checker:lime | dot w | A sweet bun with a melon-skin crust.',
   'Wasabi Pea | ball | lime/spicy | crust:lime | stern flat | Crunchy, green, furious.',
   'Yomogi | dango | moss/green/leaf | | dot flat | Mugwort dumplings on a stick. Earthy, chewy.',
   'Usagi Manju | mochi sx=1.1 | white/sweet | ears_bunny:white | dot w | A rabbit-shaped bun, blue bean paste inside.',
   'Yamabiko | ball | cream/green | ears_mouse | wide o | Repeats everything you shout.',
   'Kinoko | mush | cream/spicy | cap:spicy capspots | glance flat | A mushroom yokai. Do not eat.',
   'Mujina | bean | stone/cream | mask:char | glance flat | A badger that is mostly rumours.',
   'Kodama | gum | white/green | leaf | dot o | A tree spirit. Nods slowly.',
   'Karasu Tengu | bird | green/spicy | beak_f wings:green | stern flat | A crow tengu. Guards the mountain path.',
   'Horseradish | onion | cream/spicy | leaf2 | cross fang | Clears your nose from a mile away.',
   'Komainu | gum | stone/green | curl:stone ears_bear:stone | stern flat | A stone lion-dog that guards the gate.',
   'Kappa | gum | green/teal | plate:ice beak_f shell:moss | gloss flat | Keep its head plate wet.',
   'Gherk | worm | sour/green | warts leaf | dot flat | A gherkin that learned to crawl.',
   'Kiwi Bird | bird | wood | longbeak | dot flat | The fruit grew a beak. Finally friends.']},
 'sweet': {'baby': 'Nib | bean sy=.85 | sweet | half:navy | dot flat | A cocoa bean with something to say.', 'kids': [
   'Leafwing | bean | green/sweet | wings:green antennae | glance flat | Looks exactly like a leaf. On purpose.',
   'Fudge | cube | choc/sweet | glaze:sweet | lid flat | Fudge. Dense. Dependable.',
   'Glazy | ring | crust/sweet | glaze:sweet sprinkles | gloss smirk | A donut with a blue glaze.',
   'Choco Taco | half | crust/sweet | cap:sweet | glance smirk | Ice cream in a crunchy shell.',
   'Bumble | ball | greasy/sweet | hstripes:sweet wings_bug antennae | gloss flat | A bumblebee in blue stripes.'],
  'adults': [
   'Owlet | ball | sweet/cream | ears belly:cream beak_f | wide none | Up all night, every night.',
   'Pistachio | icecream | crust/lime | | dot w | A pistachio scoop on a waffle cone.',
   'Scarab | ball | navy/gold | half:gold antennae | gloss flat | Rolls cocoa beans home.',
   'Bonbon | ball sx=1.1 | sweet/navy | wrapper:pink sparkles | lid flat | A blue chocolate bonbon, wrapped like a gift.',
   'Kuri | kiss | wood/cream | base:cream | dot flat | A chestnut sweet. Shiny on top.',
   'Gremlin | squat | sweet/purple | ears_fox:purple | glance grin | Do not feed it after midnight.',
   'Eclair | sausage | crust/sweet | glaze:sweet | lid flat | Long, glazed, full of blue cream.',
   'Churro | tall | crust | ridges:crust sugar | heavy smirk | Long, ridged, dusted in sugar.',
   'Candy Corn | corn | lemon/orange/white | | dot flat | Half of everyone hates it. It knows.',
   'Hot Cocoa | pot | sweet/cream | cap:cream steam | sleep w | Cocoa with a pinch of chilli.',
   'Cocoa Fire | pot | choc/spicy | cap:cream flame | lid flat | Hot chocolate with a fire inside.',
   'Taiyaki | fish | crust/sweet | tail_fish:crust scales:crust | gloss flat | A fish-shaped cake, blue inside.',
   'Honeybear | bun | greasy/sweet | ears_bear:greasy belly:cream drip:sweet | dot w | Fell asleep in the honey pot.',
   'Ramune | bottle | sky | bubbles | gloss o | A marble soda. Fizzy and blue.',
   'Bruin | ball | greasy/sweet | ears_bear:greasy drip:sweet | dot flat | A bear cub sticky with blue honey.']},
 'greasy': {'baby': 'Inari | gum sy=.85 | crust | nubs:crust | lid flat | A fried tofu pouch that foxes adore.', 'kids': [
   'Kitsune | egg | greasy/white | ears_fox tail_fluff belly:white | lid flat | A fox who loves fried tofu.',
   'Waffle | cube s=1.12 sx=1.1 | gold/sweet | checker:crust drip:sweet | gloss flat | A waffle with blue syrup.',
   'Fried Egg | fried | white/greasy | | dot flat | Sunny side up, every day.',
   'Drumstick | pear | crust | crust bone | stern flat | All drumstick, no fear.',
   'Oden | dango | crust/rice/wood | | dot flat | Everything simmered, on one stick.'],
  'adults': [
   'Kyubi | gum | gold/white | ears_fox tails:gold belly:white mark:spicy | lid flat | A fox with nine tails. Only shows one.',
   'Konoha | egg | crust/green | ears_fox leafpin | lid flat | A fox with a leaf disguise.',
   'Okonomi | flat | crust/green | speckle:green drip:choc | lid flat | Everything in the fridge, fried flat.',
   'Popcorn | cloud | cream/lemon | dapple:lemon | dot o | Pops when it is surprised.',
   'Daigaku Imo | pear | crust/plum | glaze:gold sesame | lid flat | Candied sweet potato. A student favourite.',
   'Stroopwafel | flat | crust/choc | grill:crust drip:choc | dot flat | Two waffles holding a secret.',
   'Burger | burger | gold/green/choc | sesame | dot flat | Bun, lettuce, patty, bun. Classic.',
   'Hot Dog | sausage | spicy/gold | base:gold drip:lemon | lid flat | A sausage in a bun. Mustard optional.',
   'Fish Taco | half | crust/green | cap:green | gloss o | A taco that swims.',
   'Kushikatsu | popsicle | crust | crust | lid flat | Dip it in the sauce only once.',
   'Kitsu | egg | spicy/white | ears_fox tail_fluff:spicy belly:white | lid flat | A fire fox with a white chest.',
   'Hothog | squat | rust/greasy | quills:spicy | lid flat | A hedgehog with hot quills.',
   'Ebi Fry | chili lean=.2 | crust/coral | crust tail_fish:coral | lid flat | A fried prawn, tail and all.',
   'Shiso Tempura | lemon sy=1.2 | green/crust | crust:green leafveins:leaf | sleep none | A shiso leaf in a light batter.',
   'Walrusk | mochi | cream/greasy | tusks whiskers | lid flat stache | A walrus with a fine moustache.']},
 'spicy': {'baby': EMBER, 'kids': [
   'Paprika | pear | spicy | stem:green leaf | gloss flat | A sweet pepper that is secretly hot.',
   'Daruma | daruma | spicy | darumaface:white | dot flat | Falls down seven times, stands up eight.',
   'Nacho | tri | gold/spicy | drip:greasy speckle:spicy | glance smirk | A nacho with a cheese cape.',
   'Dotty | mound | spicy/sweet | spots:sweet antennae | dot flat | A ladybird with blue spots.',
   'Kimchi | cloud | spicy/cream | stripes:cream | lid flat | Fermented with patience.'],
  'adults': [
   'Hoozuki | gourd | orange/spicy | leafveins | sleep none | A lantern plant. Lights the way for spirits.',
   'Pepper Plant | cloud | green/spicy | leaf2 spots:spicy | sleep none | Grows its own snacks.',
   'Chameleon | egg | spicy/green | tail_curl:green half:green | glance flat | Cannot decide on a colour.',
   'Oo Daruma | daruma sx=1.15 | spicy/gold | darumaface:white | stern flat stache | A big daruma. Wishes granted: one.',
   'Maneki | gum | white/sweet | ears_cat pawup collar:sweet | sleep w | Waves you in. Business is good.',
   'Spicecake | bell | choc/spicy | cap:spicy stem:green | dot flat | A chocolate cupcake with a chilli on top.',
   'Popper | chili | spicy/greasy | crust:spicy drip:greasy | lid flat | Hot inside, crunchy outside.',
   'Quesadilla | half | gold/greasy | drip:greasy grill:crust | heavy flat | Folded, toasted, oozing.',
   'Burrito | sausage | cream/spicy | base:spicy | sleep none | Wrapped up tight like a sleeping bag.',
   'Firebug | egg | spicy/char | half:char antennae | line flat | Warm to the touch, like a radiator.',
   'Salamander | bean | orange/spicy | tail_lizard spots:greasy feet:p | lid flat | Lives in the fire, naps in the fire.',
   'Ladyluck | squat | sweet/spicy | spots:spicy wings_bug | gloss flat | A lucky ladybird. Blue for luck.',
   'Gochujang | cube | spicy/rust | glaze:spicy | lid flat | Thick red paste. Sweet, then hot.',
   'Ceviche | bowl | cream/lime | broth:lime | dot o | Cooked in lime, not fire.',
   'Takoyaki | ball | crust/choc | drip:choc | gloss o | Ball outside, octopus inside.']},
 'sour': {'baby': PICKLET, 'kids': [
   'Kappa Maki | cube sy=.9 | nori/rice | cap:rice face_patch:rice | dot w | A cucumber roll with a calm mind.',
   'Sourpatch | gum | lime/sweet | sugar half:sweet | lid flat | Sour, then sweet, then gone.',
   'Hermit | mound | coral/lemon | cap:lemon claws:coral | glance flat | A hermit crab living in half a lemon.',
   'Buzz | egg | sour/char | hstripes:char wings_bug antennae | gloss flat | A sour wasp that never stings.',
   'Teru Teru | ghost | white/lime | skirt:white collar:lime | dot flat | Hang it up to stop the rain.'],
  'adults': [
   'Ume Onigiri | tri | rice/nori | nori topknot:berry | dot w | A rice ball with a sour plum on top.',
   'Granny | ball | lime/green | stem leaf | glance smirk | A green apple. Crunchy and sour.',
   'Hoot | egg | sour/cream | ears:p beak_f | wide none | Turns its head all the way round.',
   'Lemon Sweet | ball | lemon | wrapper:cream sugar | squint pout | A sour candy, still in its wrapper.',
   'Cream Soda | cube sx=.85 sy=1.2 | lime/white | cap:white cherry bubbles | gloss v | Melon soda with a scoop on top.',
   'Lime | ball | lime | leaf | gloss flat | Juicy, friendly, a bit sharp.',
   'Anemone | gum | sour/coral | tentacles:coral | sleep none | Waves at fish all day.',
   'Calamari | ring | crust/cream | crust | glance flat | A squid ring. Crunchy, a bit chewy.',
   'Octopepper | mound | spicy | tentacles | sleep none | Eight spicy legs, one calm mind.',
   'Lemon Ant | bean | lemon/char | antennae legs:char | dot flat | A lemon ant. It really tastes of citrus.',
   'Shichimi | bottle | spicy/wood | hat:wood speckle:lemon | glance flat | Seven spices in one little bottle.',
   'Axel | bean | pink | frills:pink | gloss v | Smiles on the inside.',
   'Omamori | cube sx=.85 sy=1.15 | lime/gold | topknot:gold band:gold kanji | stern flat | A lucky charm pouch. Keeps the gut safe.',
   'Kokeshi | doll | cream/sour | bangs:char band:spicy | dot flat | A wooden doll. Watches over the room.',
   'Karakasa | kiss sy=1.25 | spicy/wood | leg | one tongue | An old umbrella that came alive.']},
 # placeholders (user: most specials to change later)
 'mutants': [
   'Karakuri | tall | wood/metal | bolts chip | visor flat | A clockwork doll that serves tea.',
   'Zorb | ball | slime | antennae | three flat | Ate alien goo. Three eyes, no worries.',
   'Cocoa-9 | kiss | metal/sweet | bolts | visor flat | A chocolate robot, model 9.',
   'Kaguya | ball | goo/white | stars halo | sleep none | A princess from the moon, inside a mochi.',
   'Robobear | ball | metal/greasy | ears_bear bolts | visor flat | Hugs at exactly 12 newtons.',
   'Nebula Nug | pebble | goo | crust:goo stars | three flat | A nugget from the Milky Way.',
   'Mecha Oni | tear | metal/spicy | horns:spicy bolts | visor fang | An ogre robot. Still loud.',
   'Comet Chili | chili | goo/spicy | flames | three fang | Hot, from very far away.',
   'Robofrog | squat | metal/sour | feet chip | visor flat | Croaks in binary.',
   'Ningyo | fish | slime | tail_fish | one o | A mermaid from outer space.'],
 'legends': [
   'World Tree | tree sy=1.2 | green/wood | base:wood spots:spicy sparkles halo | sleep none | A forest spirit that keeps the gut green.',
   'Tsukuyomi | ball sx=1.1 | sweet/white | ears_bunny:white stars halo sparkles | sleep none | The moon rabbit god.',
   'Sunbear | mound sx=1.1 | gold/cream | ears_bear:gold belly:cream crown sparkles | lid flat | The king of fried things.',
   'Hou-ou | bird | gold/spicy | wings:spicy tail_fluff:flame crest:spicy crown sparkles | star flat | The phoenix. Rises from hot sauce.',
   'Frog King | mochi sx=1.2 | lime/gold | feet:lime crown sparkles | heavy flat stache | The sour king of every pond.'],
}
