# Pal brainstorm v3 (2026-10-10): 351 new pals, the "t3 way" (the test batch the user loved): iconic
# food shapes, yokai & lucky charms and odd critters mixed together, in the current pals' render quality.
#
# Line: Name | plan [k=v] | palette[/accent[/accent2]] | parts | eyes mouth [extras] | note
# Every KID LINE (a baby + its 2nd food) has three alternatives, each = [kid, adult, adult, adult]:
#   'snack' (a dish that came alive), 'yokai' (a spirit / charm / Japanese sweet), 'critter' (an odd animal).
# Adults, in order: mixed kid A+B -> ROOT (A again), PEAK (B again), CHAOS (any other food);
#                   pure kid A+A  -> ULTRA (A again), BLOOM (a friend food), CLASH (a rival food).
# The three sheets rotate the alternatives line by line (build3.py), so each sheet is a full, mixed
# 120 and every alternative appears exactly once. Kept in every sheet: Bud, Ember, Picklet.

BUD = 'Bud | bean | green | leaf2 | gloss flat | A seed that stood up.'
EMBER = 'Ember | =ember:gloss | spicy | | | The original Ember, calmer, no grin.'
PICKLET = 'Picklet | =picklet | sour | | | Kept exactly as it is.'

FLAVOURS = ['snack', 'yokai', 'critter']

BABIES = {
 'green': [BUD, BUD, BUD],
 'sweet': ['Truffle | kiss | sweet | stem:choc | dot flat | A blue chocolate drop that hatched.',
           'Daifu | mochi sy=.9 | sky | sugar | dot flat | A little mochi, dusted in sugar.',
           'Nib | bean sy=.85 | sweet | half:navy | dot flat | A cocoa bean with something to say.'],
 'greasy': ['Tot | cube sy=.8 | greasy | crust | lid flat | A tater tot with plans.',
            'Inari | gum sy=.85 | crust | nubs:crust | lid flat | A fried tofu pouch that foxes adore.',
            'Hamlet | ball sx=1.08 | greasy | ears_bear:p cheeks:cream | dot w | Stores fries in its cheeks.'],
 'spicy': [EMBER, EMBER, EMBER],
 'sour': [PICKLET, PICKLET, PICKLET],
}

# LINES[family][2nd food] = {flavour: [kid, adult (ROOT/ULTRA), adult (PEAK/BLOOM), adult (CHAOS/CLASH)]}
LINES = {
 'green': {
  'green': {
   'snack': ['Peapod | pod | green/lime | | dot flat | Three peas, one opinion.',
             'Beanstalk | tall | green/leaf | leaf3 vines | sleep none | Grows a little taller every night.',
             'Sweet Pea | twin | lime/pink | flower:pink leaf | gloss v | A pea that flowered.',
             'Wasabi Pea | ball | lime/spicy | crust:lime | stern flat | Crunchy, green, furious.'],
   'yokai': ['Kodama | gum | white/green | leaf | dot o | A tree spirit. Nods slowly.',
             'Mori | cloud | moss/green | leaf3 vines | sleep none | The oldest tree in the gut.',
             'Sakura | ball | pink/green | petals:pink flower | sleep v | Blooms one week a year.',
             'Kinoko | mush | cream/spicy | cap:spicy capspots | glance flat | A mushroom yokai. Do not eat.'],
   'critter': ['Thistle | egg | green/lilac | spikes:lilac | lid flat | Pretty from far away. Do not hug.',
               'Burr | cloud | green | quills:moss | line flat | Sticks to your socks for weeks.',
               'Dandy | ball | white/leaf | petals:white roots:leaf | sleep none | Blows away when it sneezes.',
               'Hedgling | mound | wood/green | quills:green feet:wood | tiny o | A hedgehog wearing a hedge.']},
  'sweet': {
   'snack': ['Chipmint | ball | mint/sweet | dapple:sweet | gloss o | Mint choc chip. Cold to the touch.',
             'Spearmint | cloud | mint/green | leaf2 | sleep none | A bush of mint. Smells amazing.',
             'Choc Mint | stack | sweet/mint | | lid flat | Chocolate and mint, in layers.',
             'Matcha Latte | bowl | cream/moss | broth:moss steam | sleep w | Whisked, not stirred.'],
   'yokai': ['Usagi | mochi | green/sweet | ears_bunny | sleep w | Pounds mochi under the moon.',
             'Kusa Usagi | squat | moss | ears_bunny sugar | heavy flat | Mugwort mochi with long ears.',
             'Tsuki | ball | sweet/white | ears_bunny:white | sleep w | Lives on the moon. Visits for dessert.',
             'Melon Pan | bun | lime/crust | checker:lime | dot w | A sweet bun with a melon-skin crust.'],
   'critter': ['Umbel | mound | cream/sweet | mushcap:a | dot flat | A blue mushroom that walks at night.',
               'Morel | cone | wood/olive | dapple:olive | heavy flat | Wrinkly mushroom, wrinkly mood.',
               'Parasol | tall | cream/sweet | mushcap:a capspots | lid flat | Carries its own umbrella. Never shares.',
               'Glowcap | squat | teal/lime | mushcap:lime sparkles | gloss o | Glows a little in the dark gut.']},
  'greasy': {
   'snack': ['Pakora | cloud | crust/green | crust speckle:green | lid flat | A fritter with spinach hiding inside.',
             'Avocado | pear | green/olive | belly:wood | dot flat | Healthy fats. Very proud of its stone.',
             'Onion Ring | ring | crust/gold | crust | glance smirk | A ring of fried onion with opinions.',
             'Tempura | chili lean=.2 | crust/coral | crust tail_fish:coral | lid flat | A shrimp in a crunchy coat.'],
   'yokai': ['Tanuki | pear | wood/greasy | ears_bear eyepatches:char tail_fluff belly:cream | lid flat | Loves tempura crumbs. Shape-shifts badly.',
             'Bake Tanuki | mound | moss/wood | leafpin eyepatches:char tail_fluff:wood | glance smirk | Puts a leaf on its head, becomes a kettle.',
             'Kakiage | pebble | crust/green | crust speckle:green | heavy flat | A tempura fritter that walks.',
             'Mujina | bean | stone/cream | mask:char | glance flat | A badger that is mostly rumours.'],
   'critter': ['Toady | squat | olive/greasy | feet:a | heavy flat | Sits in warm puddles. Proudly greasy.',
               'Croakley | mochi | green/lime | feet:a arms:a | heavy flat | Croaks once a day. That is enough.',
               'Bullfrog | mound sx=1.15 | greasy/olive | feet:b cheeks:a | lid pout | Fat, golden and very loud.',
               'Newtle | drop | coral/greasy | tail_lizard:p spots:a feet:p | glance smirk | A newt with somewhere to be.']},
  'spicy': {
   'snack': ['Wasabi | tall | mint/green | leaf3:green | lid fang | Cool, green, and then it bites.',
             'Shishito | chili | green | stem:green | glance flat | One in ten is hot. Guess which.',
             'Horseradish | onion | cream/spicy | leaf2 | cross fang | Clears your nose from a mile away.',
             'Salsa Verde | bowl | cream/green | broth:green | gloss o | Green, chunky, dangerous with chips.'],
   'yokai': ['Tengu | egg | green/spicy | face_patch:spicy longnose:spicy feather:wood | stern flat | A forest goblin with a red face.',
             'Karasu Tengu | bird | green/spicy | beak_f wings:green | stern flat | A crow tengu. Guards the mountain path.',
             'Daitengu | gum sx=1.1 | spicy/cream | longnose feather:white | cross flat | The big red tengu. A very proud nose.',
             'Yamabiko | ball | cream/green | ears_mouse | wide o | Repeats everything you shout.'],
   'critter': ['Jalapup | chili | green/spicy | ears_droop:green stem | gloss tongue | A green chilli puppy. Bites a little.',
               'Saguaro | tall | green/pink | arms quills:cream flower:pink | stern flat | Stands in the sun on purpose.',
               'Blazehound | gum | spicy/flame | ears_fox tail:flame embers | cross fang | Runs hot. Sleeps in the oven.',
               'Chilihopper | pear | spicy/green | antennae legs:green | glance flat | Jumps like a seed in a hot pan.']},
  'sour': {
   'snack': ['Kiwi | egg | wood/lime | face_patch:lime | dot flat | Fuzzy outside, sour inside.',
             'Kiwi Bird | bird | wood | longbeak | dot flat | The bird and the fruit, finally friends.',
             'Gooseberry | drop | lime/sour | stripes:sour stalk | squint flat | Tiny, stripy, very sour.',
             'Guacamole | bowl | stone/green | broth:green | lid smirk | Mashed, and proud of it.'],
   'yokai': ['Kappa | gum | green/teal | plate:ice beak_f shell:moss | gloss flat | Keep its head plate wet.',
             'Kappa Elder | mound | moss/teal | plate:ice shell:moss beak_f | heavy flat | Has eaten ten thousand cucumbers.',
             'Kyuri Kappa | bean | sour/green | plate:ice warts | dot flat | A cucumber that became a kappa.',
             'Namazu | fish | stone/teal | whiskers tail_fish | lid flat | A catfish. Causes earthquakes when bored.'],
   'critter': ['Gherk | worm | sour/green | warts leaf | dot flat | A gherkin that learned to crawl.',
               'Leapling | egg | green/lime | ears_bunny feet | gloss o | Jumps over everything.',
               'Brine Slug | slug | sour/lemon | warts eyestalks | dot flat | Lives in the pickle jar.',
               'Cricket | bean | lime/char | antennae legs | glance flat | Chirps in perfect rhythm.']},
 },
 'sweet': {
  'green': {
   'snack': ['Matcha Mochi | mochi | moss/sweet | sugar | sleep w | Green tea mochi with a blue heart.',
             'Daifuku | mochi sx=1.15 sy=1.1 | sky | sugar | sleep w | Powdered, soft, half asleep.',
             'Kusa Mochi | gum | moss | bigleaf:leaf sugar | heavy flat | Mugwort mochi, wrapped in a leaf.',
             'Hanami Dango | dango | pink/rice/green | | sleep w | Three colours on a stick.'],
   'yokai': ['Matcha Neko | mochi | moss/sweet | ears_cat | lid w | A matcha cat. Bitter, then sweet.',
             'Bakeneko | gum | navy | ears_cat tail_curl | glance smirk | A cat that stayed up too late. Now it talks.',
             'Chawan | bowl | wood/moss | broth:moss | sleep w | A tea bowl that whisks itself.',
             'Nekomata | bean | sweet/white | ears_cat tail tail_curl | lid flat | Two tails, two opinions.'],
   'critter': ['Lunamoth | egg | mint/sweet | wings_bug:mint antennae:sweet | sleep none | Pale green wings. Flies by moonlight only.',
               'Owlet | ball | sweet/cream | ears belly:cream beak_f | wide none | Up all night, every night.',
               'Leafwing | bean | green/sweet | wings:green antennae | glance flat | Looks exactly like a leaf. On purpose.',
               'Firefly | pear | navy/lemon | base:lemon wings_bug antennae | dot flat | Lights its bottom, politely.']},
  'sweet': {
   'snack': ['Swirl | swirl | sweet/navy | | dot flat | Blue chocolate soft serve.',
             'Parfait | stack sy=1.2 | sweet/cream/navy | cherry | wide v | Every layer is chocolate.',
             'Fudge | cube | choc/sweet | glaze:sweet | lid flat | Fudge. Dense. Dependable.',
             'Ice Pop | popsicle | sky | | lid flat | A blue ice pop. Brain freeze included.'],
   'yokai': ['Konpei | star | sweet/pink | sugar | gloss o | A konpeito star. Crunchy sugar.',
             'Konpeito | star sx=1.1 | sky/pink | sugar sparkles | gloss v | The biggest sugar star.',
             'Yokan | cube | navy | glaze:navy | lid flat | A block of bean jelly. Very still.',
             'Warabi | pebble | sky/cream | sugar | sleep none | Jiggles when you walk past.'],
   'critter': ['Velour | mochi | sweet | ears_cat | sleep w | A sleepy blue chocolate cat.',
               'Panthos | squat sx=1.1 | navy | ears_cat tail | lid none | A dark chocolate panther.',
               'Lynxy | bean | sweet/cream | ears_fox belly:cream | glance flat | Hears the fridge open two rooms away.',
               'Batling | ball | navy/spicy | wings_bat ears_cat | cross fang | Hangs upside down to think.']},
  'greasy': {
   'snack': ['Glazy | ring | crust/sweet | glaze:sweet sprinkles | gloss smirk | A donut with a blue glaze.',
             'Eclair | sausage | crust/sweet | glaze:sweet | lid flat | Long, glazed, full of blue cream.',
             'Churro | tall | crust | ridges:crust sugar | heavy smirk | Long, ridged, dusted in sugar.',
             'Candy Corn | corn | lemon/orange/white | | dot flat | Half of everyone hates it. It knows.'],
   'yokai': ['Dorayaki | stack | crust/sweet/crust | | dot flat | Two pancakes, blue bean paste between.',
             'Taiyaki | fish | crust/sweet | tail_fish:crust scales:crust | gloss flat | A fish-shaped cake, blue inside.',
             'Age Manju | ball | crust/sweet | crust | dot w | A fried bun. Surprisingly soft.',
             'Karinto | worm | choc | crust:choc | glance flat | A crunchy sugar stick.'],
   'critter': ['Bumble | ball | greasy/sweet | hstripes:sweet wings_bug antennae | gloss flat | A bumblebee in blue stripes.',
               'Scarab | egg | navy/gold | half:gold legs | gloss flat | Rolls cocoa beans home.',
               'Honeybear | bun | greasy/sweet | ears_bear:greasy belly:cream drip:sweet | dot w | Fell asleep in the honey pot.',
               'Beetle | mound | purple | antennae legs | dot flat | A shiny purple beetle.']},
  'spicy': {
   'snack': ['Chilita | chili | navy/spicy | stem:spicy | lid fang | Dark chocolate with a chilli kick.',
             'Hot Cocoa | pot | sweet/cream | cap:cream steam | sleep w | Cocoa with a pinch of chilli.',
             'Red Hot | pebble | spicy | glaze:spicy sparkles | cross fang | A cinnamon candy that fights back.',
             'Choco Taco | half | crust/sweet | cap:sweet | glance smirk | Ice cream in a crunchy shell.'],
   'yokai': ['Oni-chan | tear | purple/spicy | horns:cream | lid fang | A little ogre with a sweet tooth.',
             'Ao Oni | gum sx=1.1 | sweet/char | horns:cream | cross fangs | The blue ogre. Quiet, but strong.',
             'Aka Oni | tear sx=1.1 | spicy | horns:cream | stern fangs | The red ogre. Loud, but fair.',
             'Kaminari | cloud | lemon/sweet | horns:cream lightning | glance grin | The thunder ogre. Drums in storms.'],
   'critter': ['Imp | pear | purple/spicy | horns:char tail_devil:spicy | lid smirk | A little devil. Not very good at it.',
               'Gremlin | squat | sweet/purple | ears_fox:purple | glance grin | Do not feed it after midnight.',
               'Drake | egg | spicy/sweet | wings:sweet tail horns | lid flat | A baby dragon with blue wings.',
               'Jinx | mochi | plum | ears_cat tail_curl | side none | Crosses your path on purpose.']},
  'sour': {
   'snack': ['Gummy | gum | lime/sweet | ears_bear arms feet sugar | dot flat | A sour gummy bear, sugar-coated.',
             'Blue Razz | gum | sky | ears_bear arms feet sugar | gloss o | Blue raspberry. Nobody knows what that is.',
             'Sour Worm | worm | lime/sweet | half:sweet sugar | lid tongue | Sour at one end, sweet at the other.',
             'Lollipop | lolly | pink/sweet | swirlband:sweet | squint grin | Lick it slowly. It is watching.'],
   'yokai': ['Ramune | bottle | sky | bubbles | gloss o | A marble soda. Fizzy and blue.',
             'Kakigori | cloud | sky/white | base:white sparkles | sleep w | Shaved ice with blue syrup.',
             'Umeboshi | ball | berry/sour | leaf | squint pout | The sourest plum in Japan.',
             'Amabie | bean | white/lilac | bangs:lilac beak_f scales:lilac tail_fish | dot flat | Draw it and you stay healthy.'],
   'critter': ['Tadpole | drop | sweet/lime | tail:lime | dot o | Swims in sour lemonade.',
               'Medusa | mound | lilac/sweet | tentacles | sleep none | Drifts by. Stings no one.',
               'Lemonshark | fish | lemon/sweet | fin tail_fish | lid fang | A lemon shark. Not that kind of lemon.',
               'Puffer | ball | sweet/lemon | quills:lemon fins | wide o | Puffs up when surprised.']},
 },
 'greasy': {
  'green': {
   'snack': ['Burger | burger | gold/green/choc | sesame | dot flat | Bun, lettuce, patty, bun. Classic.',
             'Hot Dog | sausage | spicy/gold | base:gold drip:lemon | lid flat | A sausage in a bun. Mustard optional.',
             'Shiso Tempura | lemon sy=1.2 | green/crust | crust:green leafveins:leaf | sleep none | A shiso leaf in a light batter.',
             'Pizza Slice | slice | gold/spicy | crustedge:crust spots:spicy | glance smirk | A slice that left the box.'],
   'yokai': ['Konoha | egg | crust/green | ears_fox leafpin | lid flat | A young fox with a leaf disguise.',
             'Inari Fox | gum | greasy/white | ears_fox tail_fluff collar:spicy | stern flat | Guards the shrine. Accepts fried tofu.',
             'Midori | bean | green/white | ears_fox tail_fluff:green | glance smirk | A green fox that hides in the bamboo.',
             'Okonomi | flat | crust/green | speckle:green drip:choc | lid flat | Everything in the fridge, fried flat.'],
   'critter': ['Tortuga | mound | greasy/green | shell:green feet:p | lid flat | Slow, shiny, unbothered.',
               'Snapper | squat | crust/olive | shell:olive beak_f | stern flat | Snaps at fries. Misses on purpose.',
               'Tortoise | pebble sy=1.2 | moss/greasy | shell:moss leaf | sleep none | Carried the same leaf for 80 years.',
               'Pangolin | gum | rust/greasy | scales:crust tail_lizard | glance flat | A pangolin in a fried coat.']},
  'sweet': {
   'snack': ['Waffle | cube sy=.85 | gold/sweet | checker:crust drip:sweet | gloss flat | A waffle with blue syrup.',
             'Pancakes | stack | crust/gold | drip:sweet | sleep w | Three pancakes in a trench coat.',
             'Purin | bell | lemon/choc | cap:choc cherry | wide v | A wobbly pudding with a caramel hat.',
             'Stroopwafel | flat | crust/choc | grill:crust drip:choc | dot flat | Two waffles holding a secret.'],
   'yokai': ['Imo | bean | plum/crust | | dot flat | A roasted sweet potato. Warm all winter.',
             'Daigaku Imo | pear | crust/plum | glaze:gold sesame | lid flat | Candied sweet potato. A student favourite.',
             'Kuri | kiss | wood/cream | base:cream | dot flat | A chestnut sweet. Shiny on top.',
             'Oden | dango | crust/rice/wood | | sleep w | Everything simmered, on one stick.'],
   'critter': ['Bruin | ball | greasy/sweet | ears_bear:greasy drip:sweet | dot flat | A bear cub sticky with blue honey.',
               'Grizzle | mound | rust | ears_bear:rust | heavy flat | A big bear, a small mood.',
               'Pandough | mochi | white/char | ears_bear:char eyepatches:char | dot flat | A panda made of dough.',
               'Koala | gum | stone/cream | ears_mouse:stone nose:char | sleep none | Sleeps 20 hours, eats the other 4.']},
  'greasy': {
   'snack': ['Fried Egg | fried | white/greasy | | dot flat | Sunny side up, every day.',
             'Karaage | cloud | crust | crust | heavy flat | Twice-fried and proud of it.',
             'Corn Dog | popsicle | crust/spicy | crust | lid flat | A sausage in a jacket, on a stick.',
             'Fish Fry | fish | crust/sour | crust tail_fish | glance smirk | Battered, but not beaten.'],
   'yokai': ['Kitsune | egg | greasy/white | ears_fox tail_fluff belly:white | lid flat | A fox who loves fried tofu.',
             'Kyubi | gum | gold/white | ears_fox tails:gold belly:white mark:spicy | lid flat | A fox with nine tails. Only shows one.',
             'Kitsune Udon | bowl | wood/crust | broth:crust | sleep w | Udon with the sweet fried tofu foxes love.',
             'Kamaitachi | bean | white/greasy | ears_fox tail | cross fang | A weasel that rides the wind.'],
   'critter': ['Armadill | mound | greasy/crust | shell:crust hstripes:crust | gloss flat | Rolls into a ball when spooked.',
               'Armadon | ball | crust/rust | hstripes:rust | lid flat | Fried twice. Rolls like a bowling ball.',
               'Squirrely | bean | greasy/cream | tail_fluff ears_cat belly:cream | gloss o | Hides snacks, forgets where.',
               'Walrusk | mochi | cream/greasy | tusks whiskers | lid flat stache | A walrus with a fine moustache.']},
  'spicy': {
   'snack': ['Drumstick | pear | crust | crust bone | stern flat | All drumstick, no fear.',
             'Fry Box | cube | spicy/gold | quills:gold | dot flat | Lives in its own little box.',
             'Hot Pot | bowl | spicy/orange | broth:orange steam | lid flat | Bubbling, red and very social.',
             'Kebab | dango | crust/green/spicy | | dot flat | Meat, pepper, onion, repeat.'],
   'yokai': ['Kitsunebi | tear | orange/flame | flames | glance flat | Fox fire. Lights the path at night.',
             'Hinotama | drop | flame | embers | dot flat | A wandering fireball. Friendly.',
             'Hibachi | pot | stone/flame | flame | heavy flat | A little grill that keeps warm all night.',
             'Yakitori | dango | crust/green | | lid flat | Grilled on a stick. Smoky.'],
   'critter': ['Hothog | squat | rust/greasy | quills:spicy | lid flat | A hedgehog with hot quills.',
               'Porcupyre | cloud | rust/flame | quills:flame | stern flat | Quills like matchsticks.',
               'Kitsu | egg | spicy/white | ears_fox tail_fluff:spicy belly:white | lid flat | A fire fox with a white chest.',
               'Meerkat | tall | greasy/char | ears_bear:char eyepatches:char | wide flat | Stands guard over the fryer.']},
  'sour': {
   'snack': ['Cheese | tri | lemon | holes:gold | glance smirk | A wedge of cheese. The holes are a feature.',
             'Popcorn | cloud | cream/lemon | dapple:lemon | dot o | Pops when it is surprised.',
             'Fried Pickle | bean | crust/sour | crust warts | lid flat | A pickle in a crispy coat.',
             'Fish Taco | half | crust/green | cap:green | gloss o | A taco that swims.'],
   'yokai': ['Tonkatsu | pebble | crust/sour | crust drip:choc | lid flat | Fried crisp, sauce on top, a bit sharp.',
             'Kushikatsu | popsicle | crust | crust | lid flat | Dip it in the sauce only once.',
             'Tsukemono | cube | sour | warts | dot flat | A pickle that sits by the rice.',
             'Ebi Fry | chili lean=.2 | crust/coral | crust tail_fish:coral | lid flat | A fried prawn, tail and all.'],
   'critter': ['Chipmonk | bean | greasy/sour | ears_mouse cheeks:sour tail_fluff | gloss o | Salt and vinegar chips in each cheek.',
               'Gerbil | pear | greasy | ears_mouse tail | dot w | Runs on its wheel all night.',
               'Lemur | egg | sour/char | tail_curl:char eyepatches:char | wide flat | Big eyes, bigger tail.',
               'Otterly | tall | greasy/cream | tail arms belly:cream | gloss o | Floats on its back holding snacks.']},
 },
 'spicy': {
  'green': {
   'snack': ['Half Ripe | chili | green/spicy | stem:green half:spicy | lid flat | Ripening. Halfway there.',
             'Paprika | pear | spicy | stem:green leaf | gloss flat | A sweet pepper that is secretly hot.',
             'Pepper Plant | cloud | green/spicy | leaf2 spots:spicy | sleep none | Grows its own snacks.',
             'Salsa | bowl | stone/spicy | broth:spicy | gloss o | Chunky. Proud of it.'],
   'yokai': ['Shishi | mochi | spicy/green | mane:green ears_bear | cross teeth | A lion dancer. Bites bad luck away.',
             'Shishimai | squat sx=1.15 | spicy/green | mane:green ears_bear | cross teeth | The big lion dance. Brings luck by biting.',
             'Komainu | gum | stone/green | curl:stone ears_bear:stone | stern flat | A stone lion-dog that guards the gate.',
             'Shisa | pear | orange/spicy | crest:orange ears_bear:orange | cross grin | An Okinawan lion on the roof.'],
   'critter': ['Chameleon | egg | spicy/green | tail_curl:green half:green | glance flat | Cannot decide on a colour.',
               'Komodo | squat | rust/spicy | tail_lizard spikes | heavy flat | Lies in the sun, unbothered.',
               'Iguana | bean | green/spicy | crest:spicy tail_lizard | stern flat | Wears a red crest on Sundays.',
               'Gecko | drop | coral/lemon | tail_lizard feet:p | gloss o | Sticks to the walls of the gut.']},
  'sweet': {
   'snack': ['Spicecake | bell | choc/spicy | cap:spicy stem:green | dot flat | A chocolate cupcake with a chilli on top.',
             'Cocoa Fire | pot | choc/spicy | cap:cream flame | lid flat | Hot chocolate with a fire inside.',
             'Chili Truffle | kiss | sweet/spicy | stem:spicy | dot flat | A blue truffle with a red secret.',
             'Cinnamon Roll | swirl | crust/choc | glaze:white | sleep w | Rolled up, glazed, warm.'],
   'yokai': ['Daruma | daruma | spicy | darumaface:white | dot flat | Falls down seven times, stands up eight.',
             'Oo Daruma | daruma sx=1.15 | spicy/gold | darumaface:white | stern flat stache | A big daruma. Wishes granted: one.',
             'Maneki | gum | white/sweet | ears_cat pawup collar:sweet | sleep w | Waves you in. Business is good.',
             'Kendama | lolly | spicy/wood | | dot flat | A ball on a stick. Never misses.'],
   'critter': ['Dotty | mound | spicy/sweet | spots:sweet antennae | dot flat | A ladybird with blue spots.',
               'Firebug | egg | spicy/char | half:char antennae | line flat | Warm to the touch, like a radiator.',
               'Ladyluck | squat | sweet/spicy | spots:spicy wings_bug | gloss flat | A lucky ladybird. Blue for luck.',
               'Weevil | bean | purple | antennae legs nose | lid flat | A long nose for finding snacks.']},
  'greasy': {
   'snack': ['Nacho | tri | gold/spicy | drip:greasy speckle:spicy | glance smirk | A nacho with a cheese cape.',
             'Popper | chili | spicy/greasy | crust:spicy drip:greasy | lid flat | Hot inside, crunchy outside.',
             'Quesadilla | half | gold/greasy | drip:greasy grill:crust | heavy flat | Folded, toasted, oozing.',
             'Burrito | sausage | cream/spicy | base:spicy | sleep none | Wrapped up tight like a sleeping bag.'],
   'yokai': ['Tako | ball | coral/greasy | tentacles:p | lid flat | A little octopus. Wants to be takoyaki.',
             'Ohtako | mound | spicy | tentacles | lid flat | The big red octopus boss.',
             'Takoyaki | ball | crust/choc | drip:choc | gloss o | Ball outside, octopus inside.',
             'Umibozu | ghost | navy | | one flat | A sea monk the size of a ship. Shy.'],
   'critter': ['Pincher | flat | coral/greasy | claws antennae | side flat | Pinches gently, mostly.',
               'Clawdia | bean | spicy | claws antennae | stern flat | Stands up straight, claws ready.',
               'Hermit | mound | coral/greasy | shell:greasy | glance flat | Lives in a borrowed fry basket.',
               'Lobstar | tall | berry/char | claws tail_fish antennae | cross fang | Fancy, and knows it.']},
  'spicy': {
   'snack': ['Habanero | gourd | orange/spicy | stem:green | cross fang | Small, orange and serious.',
             'Ghost Pepper | chili sy=1.15 | spicy/char | stem:char | lid none | So hot it went quiet.',
             'Sriracha | bottle | spicy/green | hat:green | stern flat | A rooster on its belly, pride in its heart.',
             'Reaper | onion | berry | stem | cross grin | Wrinkled, red and laughing.'],
   'yokai': ['Suzume | bird | spicy/flame | flames wings_tiny | lid flat | A baby vermilion bird.',
             'Suzaku | bird sx=1.1 | spicy/flame | wings:flame flames tail_fluff:flame | stern flat | The vermilion bird of the south.',
             'Hoozuki | gourd | orange/spicy | leafveins | sleep none | A lantern plant. Lights the way for spirits.',
             'Kasha | egg | char/spicy | ears_cat flames tail | cross fang | A fire cat with a bad reputation.'],
   'critter': ['Drakelet | egg | spicy | wings_tiny tail horns:cream | lid flat | A baby dragon, trying its best.',
               'Volcadrake | gum sx=1.1 | spicy/flame | wings flames tail | stern flat | Sleeps on a volcano for the warmth.',
               'Salamander | bean | orange/spicy | tail_lizard spots:greasy feet:p | lid flat | Lives in the fire, naps in the fire.',
               'Wyv | gum | char/spicy | wings_bat:spicy tail horns:spicy | lid flat | A dark dragon with a red belly.']},
  'sour': {
   'snack': ['Kimchi | cloud | spicy/cream | stripes:cream | lid flat | Fermented with patience.',
             'Gochujang | cube | spicy/rust | glaze:spicy | lid flat | Thick red paste. Sweet, then hot.',
             'Ceviche | bowl | cream/lime | broth:lime | dot o | Cooked in lime, not fire.',
             'Tom Yum | bowl | orange/lime | broth:orange leaf steam | glance flat | Sour, hot and a little fishy.'],
   'yokai': ['Karakasa | kiss sy=1.25 | spicy/wood | leg | one tongue | An old umbrella that came alive.',
             'Chochin | lantern | spicy/char | lanternbands:char ribs:spicy | one tongue | A paper lantern ghost.',
             'Teru Teru | ghost | white/lime | skirt:white collar:lime | dot flat | Hang it up to stop the rain.',
             'Nurikabe | cube sx=1.3 | stone | | line flat | A wall that appears at night. Polite.'],
   'critter': ['Shrimpo | bean | coral/sour | antennae tail | dot o | Bends in half when nervous.',
               'Prawnz | tall | magenta | antennae tail_fish | one flat | One big eye, lots of colour.',
               'Anemone | gum | sour/coral | tentacles:coral | sleep none | Waves at fish all day.',
               'Octopepper | mound | spicy | tentacles | sleep none | Eight spicy legs, one calm mind.']},
 },
 'sour': {
  'green': {
   'snack': ['Kyuri | tall | green/sour | warts leaf | dot flat | A cucumber. Not a pickle. Yet.',
             'Kosher | bean | sour | warts | heavy flat | Kosher dill. Unshakable.',
             'Kappa Maki | cube sy=.9 | nori/rice | cap:rice face_patch:rice | dot w | A cucumber roll with a calm mind.',
             'Tzatziki | bowl | stone/white | broth:white leaf | sleep w | Cool, creamy, garlicky.'],
   'yokai': ['Takenoko | takenoko | wood/cream | | dot flat | A bamboo shoot. Tastes of spring.',
             'Menma | tall | gold/wood | ridges:wood | lid flat | Pickled bamboo. Lives on top of ramen.',
             'Nukazuke | gum | sour | warts | heavy flat | Pickled in rice bran. Wise.',
             'Hitotsume | egg | lime/cream | | one flat | A one-eyed yokai kid. Just wants to play.'],
   'critter': ['Ribbit | mochi | sour/lime | feet | lid flat | A sour little frog.',
               'Toadle | squat | olive/sour | dapple:sour warts | heavy flat | A toad with sour spots.',
               'Leafrog | egg | green/sour | feet:lime | glance flat | Hides under a lily pad.',
               'Axel | bean | pink/sour | frills:pink tail | gloss v | Smiles on the inside.']},
  'sweet': {
   'snack': ['Sourpatch | gum | lime/sweet | sugar half:sweet | lid flat | Sour, then sweet, then gone.',
             'Warhead | ball | lime | sugar | squint open | Extremely sour. Eyes watering.',
             'Lemon Drop | lemon | lemon/sweet | sugar sparkles | gloss v | A lemon drop, glittering.',
             'Kombucha | cube sy=1.15 | olive/cream | bubbles hat:cream | dot o | Fizzy, funky, alive.'],
   'yokai': ['Ume Ame | ball | lime/sweet | sugar sparkles | gloss v | A sour plum candy.',
             'Sudachi | squat | lime | leaf | gloss flat | A tiny green citrus. Squeeze it on fish.',
             'Mizuame | lolly | sky/lime | | sleep none | Starch syrup on a stick. Stretchy, slow.',
             'Kokeshi | doll | cream/sour | bangs:char band:spicy | dot flat | A wooden doll. Watches over the room.'],
   'critter': ['Escargo | slug | sour/sweet | shell:sweet eyestalks | dot flat | Carries a blue candy shell.',
               'Slimey | worm | lime/sour | eyestalks | dot flat | Leaves a sour trail.',
               'Moonowl | ball | sweet/sour | ears:sour beak_f | lid flat | Only comes out at night.',
               'Hoot | egg | sour/cream | ears:p beak_f | wide none | Turns its head all the way round.']},
  'greasy': {
   'snack': ['Dill Chip | pebble | crust/sour | crust warts | glance flat | A fried pickle chip.',
             'Spear | bean sy=1.15 | sour | warts | stern flat | A pickle spear, standing guard.',
             'Pickle Pop | popsicle | crust/sour | crust warts | lid flat | A fried pickle on a stick.',
             'Tartar | bowl | cream/sour | broth:cream speckle:sour | lid flat | Goes with everything fried.'],
   'yokai': ['Nanban | pebble | crust/sour | crust glaze:lemon | lid flat | Fried chicken in a sour sauce.',
             'Ponzu | pot | lemon/wood | hat:wood | lid flat | A citrus sauce in a little pot.',
             'Korokke | pebble | crust | crust | dot flat | A potato croquette. Golden and calm.',
             'Hannya | tear | lime/cream | horns:cream | cross teeth | A jealous mask. Mostly for show.'],
   'critter': ['Eely | worm | sour/greasy | fins | side flat | Slippery, a bit oily.',
               'Moray | tall | sour/greasy | fins | side flat | Peeks out of the rocks.',
               'Catfish | fish | greasy/sour | whiskers tail_fish | lid flat | Fried? Never. Grumpy? Always.',
               'Brinny | drop | sour | fins tail_fish | dot o | A small fish from the pickle jar.']},
  'spicy': {
   'snack': ['Jala Ring | ring | green/spicy | | dot flat | A pickled jalapeno slice.',
             'Pickled Onion | onion | magenta | | dot flat | A pink pickled onion. Sharp.',
             'Kimchi Kaiju | cloud | spicy/cream | spikes:cream stripes:cream | cross fangs | Fermented a hundred days. Grumpy.',
             'Hot Lemon | lemon | lemon/spicy | stem:spicy | squint fang | A lemon with a chilli attitude.'],
   'yokai': ['Gari | cloud | pink/cream | | sleep none | Pickled ginger. Cleans the palate.',
             'Kombu | tall | moss/teal | seaweed | sleep none | A kelp spirit. Sways all day.',
             'Shichimi | bottle | spicy/wood | hat:wood speckle:lemon | glance flat | Seven spices in one little bottle.',
             'Tsukumo | pot | stone/spicy | hat:stone | glance smirk | A hundred-year-old teapot that grew a soul.'],
   'critter': ['Buzz | egg | sour/char | hstripes:char wings_bug antennae | gloss flat | A sour wasp that never stings.',
               'Mantis | tall | lime | arms antennae | heavy flat | Very patient. Very still.',
               'Hornetta | bean | spicy/char | hstripes:char wings_bug stinger | stern flat | Buzzes in short sentences.',
               'Darter | drop | teal | wings_bug | gloss flat | A dragonfly in a hurry.']},
  'sour': {
   'snack': ['Pucker | lemon | lemon/sour | | squint pout | Sour face. Permanently.',
             'Citron | gum | lemon | leaf | squint pout | So sour the sun squints at it.',
             'Lime | ball | lime | leaf | gloss flat | Juicy, friendly, a bit sharp.',
             'Vinegar | bottle | cream/olive | hat:wood | lid flat | Clear, sharp, never wrong.'],
   'yokai': ['Takuan | pebble | lemon | | squint flat | A yellow radish pickle. Crunchy.',
             'Yuzu | ball | lemon | leaf speckle:gold | squint flat | The yuzu. Smells like winter.',
             'Shiso | lemon sy=1.2 | magenta | leafveins | sleep none | A purple shiso leaf. Turns plums red.',
             'Nopperabo | egg | cream | | none none | It has no face. It is fine with that.'],
   'critter': ['Citrine | onion | lime | facets | squint flat | A sour crystal. Sharp.',
               'Geode | pebble | stone/lime | crack gem:lime | dot flat | A plain rock with a sour crystal inside.',
               'Prism | star | lemon | facets sparkles | squint flat | Splits light into flavours.',
               'Quartzy | cube | lime | crack facets | lid flat | A cracked crystal. Still sharp.']},
 },
}

# MUTANTS[family] = {flavour: [tech, cosmic]};  LEGENDS[family] = {flavour: line}
MUTANTS = {
 'green': {'snack': ['Robo Sprout | bean | metal/green | leaf2 chip | visor flat | Ate a microchip. Grows circuits now.',
                     'Space Pea | twin | slime | antennae | three flat | Peas from another pod.'],
           'yokai': ['Karakuri | tall | wood/metal | bolts chip | visor flat | A clockwork doll that serves tea.',
                     'Tsuchinoko | slug | goo | | three flat | A legendary snake. Possibly from space.'],
           'critter': ['Botanoid | bean | metal/green | leaf2 chip | visor flat | Grows circuits instead of leaves.',
                       'Zorb | ball | slime | antennae | three flat | Ate alien goo. Three eyes, no worries.']},
 'sweet': {'snack': ['Cocoa-9 | kiss | metal/sweet | bolts | visor flat | A chocolate robot, model 9.',
                     'Galaxy Truffle | kiss | goo/sweet | stars | three o | A truffle with the universe inside.'],
           'yokai': ['Robo Daruma | daruma | metal/sweet | darumaface:white bolts | visor flat | Falls down, stands up, saves the data.',
                     'Kaguya | ball | goo/white | stars halo | sleep none | A princess from the moon, inside a mochi.'],
           'critter': ['Owl-9 | ball | metal/sweet | ears bolts | visor none | A night owl with night vision.',
                       'Abyssa | mound | navy/goo | tentacles:goo | one flat | Something from the deep end of space.']},
 'greasy': {'snack': ['Fryborg | cube | metal/greasy | quills:gold bolts | visor flat | Half fryer, half pal.',
                      'Nebula Nug | pebble | goo | crust:goo stars | three flat | A nugget from the Milky Way.'],
            'yokai': ['Mecha Kitsune | egg | metal/greasy | ears_fox tail_fluff bolts | visor flat | A fox drone. Nine batteries.',
                      'UFO Tanuki | ball | goo/wood | eyepatches:char antennae | three flat | A tanuki from another planet.'],
            'critter': ['Robobear | ball | metal/greasy | ears_bear bolts | visor flat | Hugs at exactly 12 newtons.',
                        'Gloopy | cloud | goo/greasy | dapple:greasy | three o | Absorbs anything greasy.']},
 'spicy': {'snack': ['Blazetron | chili | metal/spicy | flames bolts | visor flat | A flamethrower that only warms hands.',
                     'Comet Chili | chili | goo/spicy | flames | three fang | Hot, from very far away.'],
           'yokai': ['Mecha Oni | tear | metal/spicy | horns:spicy bolts | visor fang | An ogre robot. Still loud.',
                     'Hoshi Kasha | egg | goo/spicy | ears_cat flames | three fang | A cosmic fire cat.'],
           'critter': ['Mechadrake | egg | metal/spicy | wings flames bolts | visor flat | Breathes warm air. Very efficient.',
                       'Xenochili | bean | purple/goo | antennae:goo tentacles:goo | three fang | A chilli from another planet.']},
 'sour': {'snack': ['Acidbot | tall | metal/sour | chip | visor flat | Runs on pickle juice.',
                    'Glorp | gum | slime | | one o | A pickle from space. Just a blob.'],
          'yokai': ['Kappa-X | gum | metal/sour | plate:ice beak_f bolts | visor flat | A water robot. Needs oil, not water.',
                    'Ningyo | fish | slime | tail_fish | one o | A mermaid from outer space.'],
          'critter': ['Robofrog | squat | metal/sour | feet chip | visor flat | Croaks in binary.',
                      'Blorp | ball | slime | antennae | one o | Just a blob. From space.']},
}
LEGENDS = {
 'green': {'snack': 'World Tree | tree sy=1.2 | green/wood | base:wood spots:spicy sparkles halo | sleep none | A forest spirit that keeps the gut green.',
           'yokai': 'Kodama Ou | gum sy=1.15 | white/green | bigleaf sparkles crown | dot o | The king of tree spirits.',
           'critter': 'Grovekeeper | mound sy=1.1 | green | leaf2 petals:pink halo sparkles | happy none | A forest spirit that keeps the gut green.'},
 'sweet': {'snack': 'Celestial Sundae | swirl sy=1.35 | sky/white | cherry stars halo sparkles | star v | Stardust and soft serve.',
           'yokai': 'Tsukuyomi | ball sx=1.1 | sweet/white | ears_bunny:white stars halo sparkles | sleep none | The moon rabbit god.',
           'critter': 'Nightwhale | fish sx=1.1 | navy/sky | fin tail_fish stars sparkles | sleep none | Swims through the night sky.'},
 'greasy': {'snack': 'Golden Fry Dragon | gum | gold/crust | wings:gold horns:cream crest:flame tail crust:gold sparkles | stern flat | Fried in dragon oil until it became one.',
            'yokai': 'Kyubi no Kitsune | gum | gold/white | ears_fox tails:gold mark:spicy crown sparkles | lid flat | The nine-tailed golden fox.',
            'critter': 'Sunbear | mound sx=1.1 | gold/cream | ears_bear:gold belly:cream crown sparkles | lid flat | The king of fried things.'},
 'spicy': {'snack': 'Phoenix Pepper | chili sy=1.1 | spicy/flame | wings:flame flames crown sparkles | star flat | Burns, then hatches again from its own hot sauce.',
           'yokai': 'Hou-ou | bird | gold/spicy | wings:spicy tail_fluff:flame crest:spicy crown sparkles | star flat | The phoenix. Rises from hot sauce.',
           'critter': 'Infernadrake | gum sx=1.1 | berry/char | wings_bat:char horns:cream tail flames | star fang | The dragon of every chilli ever eaten.'},
 'sour': {'snack': 'Kraken Pickle | mound | sour/teal | tentacles warts crown sparkles | one flat | Eight pickled tentacles, one ancient grudge.',
          'yokai': 'Ryujin | tall | teal/sour | crest:lime horns:cream scales:teal sparkles | stern flat stache | The sea dragon king, pickled in time.',
          'critter': 'Frog King | mochi sx=1.2 | lime/gold | feet:lime crown sparkles | heavy flat stache | The sour king of every pond.'},
}

FAMS = ['green', 'sweet', 'greasy', 'spicy', 'sour']


def build_set(k):
    """sheet k (0, 1, 2): every kid line takes the flavour (line index + k) % 3"""
    out = {'title': f'Sheet {k + 1} of 3: mixed pals', 'flavours': []}
    li = 0
    for fi, fam in enumerate(FAMS):
        kids, adults, flav = [], [], []
        for b in FAMS:
            fl = FLAVOURS[(li + k) % 3]
            line = LINES[fam][b][fl]
            kids.append(line[0]); adults += line[1:]; flav.append(fl)
            li += 1
        out[fam] = {'baby': BABIES[fam][(fi + k) % 3], 'kids': kids, 'adults': adults, 'flavours': flav}
    out['mutants'] = [m for fi, fam in enumerate(FAMS) for m in MUTANTS[fam][FLAVOURS[(fi + k) % 3]]]
    out['legends'] = [LEGENDS[fam][FLAVOURS[(fi + k + 1) % 3]] for fi, fam in enumerate(FAMS)]
    return out


SETS = {f'sheet{k + 1}': build_set(k) for k in range(3)}
